
package xidian.services.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://server.services.xidian/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "helloserver", targetNamespace = "http://server.services.xidian/", className = "xidian.services.webservice.Helloserver")
    @ResponseWrapper(localName = "helloserverResponse", targetNamespace = "http://server.services.xidian/", className = "xidian.services.webservice.HelloserverResponse")
    @Action(input = "http://server.services.xidian/HelloService/helloserverRequest", output = "http://server.services.xidian/HelloService/helloserverResponse")
    public String helloserver(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
